# Generated by Django 4.0.4 on 2023-06-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='details',
            field=models.CharField(default=1, max_length=333),
            preserve_default=False,
        ),
    ]
