# Generated by Django 4.0.4 on 2023-06-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='time',
        ),
    ]
