# Generated by Django 4.0.4 on 2023-06-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_cake_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chefs',
            old_name='Profession',
            new_name='profession',
        ),
        migrations.AddField(
            model_name='chefs',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='chefs',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='chefs',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
